DATA_PRESET:
  USE_CACHE: True
  USE_FULL_IMAGE: False  
  BBOX_EXPAND_RATIO: 2.5
  IMAGE_SIZE: [256, 256]
  # USE_FULL_IMAGE: True  # for fphab
  # BBOX_EXPAND_RATIO: 1.0  # for fphab
  # IMAGE_SIZE: [480, 270]  # for fphab
  CENTER_IDX: 9
  FILTER_NO_CONTACT: True
  FILTER_DIST_THRESH: 0.005

TRANSFORM:
  TRAIN:
    TYPE: SimpleTransform3DMANOObject
    AUG: True
    CENTER_JIT: 0.05
    SCALE_JIT: 0.1
    COLOR_JIT: 0.3
    ROT_JIT: 5
    ROT_PROB: 0.5
    OCCLUSION: False
    OCCLUSION_RATIO: 0

  TEST:
    TYPE: SimpleTransform3DMANOObject
    AUG: False

allmix:
  TYPE: MIX
  LENGTH: 100_000
  MIX:
    - TYPE: HO3D
      MIX_RATIO: 0.25
      VERSION: V2
      DATA_MODE: TODO
      DATA_ROOT: data
      DATA_SPLIT: TODO
      MODE_SPLIT: official

    - TYPE: HO3DYCBA
      MIX_RATIO: 0.25
      VERSION: V2
      DATA_MODE: TODO
      DATA_ROOT: data
      DATA_SPLIT: TODO
      MODE_SPLIT: official

    - TYPE: HO3DSynthT
      MIX_RATIO: 0.25
      VERSION: V2
      SYNTH_ROUND: 0
      DATA_MODE: TODO
      DATA_ROOT: data
      DATA_SPLIT: TODO
      MODE_SPLIT: official
    
    - TYPE: FilteredDexYCB
      MIX_RATIO: 0.25
      DATA_MODE: TODO
      DATA_ROOT: data
      DATA_SPLIT: TODO
      SETUP: s0
      LOAD_OBJ_ON_INIT: True
      USE_OBJ_OUTSRC: True
      SELECTED_OBJ_IDS: 
        - 010_potted_meat_can 
        - 006_mustard_bottle
        - 021_bleach_cleanser
  TRANSFORM: TODO


dexycb:
  TYPE: FilteredDexYCB
  DATA_MODE: TODO
  DATA_ROOT: data
  DATA_SPLIT: TODO
  SETUP: s0
  LOAD_OBJ_ON_INIT: True
  USE_OBJ_OUTSRC: True
  SELECTED_OBJ_IDS: 
    - 010_potted_meat_can 
    - 006_mustard_bottle
    - 021_bleach_cleanser
  TRANSFORM: TODO

ho3dv2:
  TYPE: HO3D
  VERSION: V2
  DATA_MODE: TODO
  DATA_ROOT: data
  DATA_SPLIT: TODO
  MODE_SPLIT: official
  TRANSFORM: TODO

ho3dycba:
  TYPE: HO3DYCBA
  VERSION: V2
  DATA_MODE: TODO
  DATA_ROOT: data
  DATA_SPLIT: TODO
  MODE_SPLIT: official
  TRANSFORM: TODO

ho3dsyntht:
  TYPE: HO3DSynthT
  VERSION: V2
  SYNTH_ROUND: 0
  DATA_MODE: TODO
  DATA_ROOT: data
  DATA_SPLIT: TODO
  MODE_SPLIT: official
  TRANSFORM: TODO

fphab:
  TYPE: FilteredFPHAB
  MODE_SPLIT: actions
  DATA_MODE: TODO
  DATA_ROOT: data
  DATA_SPLIT: TODO
  REDUCE_SIZE: True
  USE_JOINTS_MAGNETIC: True
  TRANSFORM: TODO