DATASET:
  TRAIN:
    TYPE: FilteredFPHAB
    DATA_MODE: 3d_hand_obj_contact
    DATA_ROOT: data
    DATA_SPLIT: train
    MODE_SPLIT: actions
    FILTER_INVISIBLE_HANDS: True
    REDUCE_SIZE: True
    USE_JOINTS_MAGNETIC: True

    TRANSFORM:
      TYPE: SimpleTransform3DMANOObject
      AUG: True
      CENTER_JIT: 0.05
      SCALE_JIT: 0.1
      COLOR_JIT: 0.3
      ROT_JIT: 5
      ROT_PROB: 0.5
      OCCLUSION: False
      OCCLUSION_RATIO: 0
  
  VAL:
    TYPE: FilteredFPHAB
    DATA_MODE: 3d_hand_obj_contact
    DATA_ROOT: data
    DATA_SPLIT: test
    MODE_SPLIT: actions
    FILTER_INVISIBLE_HANDS: True
    REDUCE_SIZE: True
    USE_JOINTS_MAGNETIC: True
    TRANSFORM:
      TYPE: SimpleTransform3DMANOObject
      AUG: False

DATA_PRESET:
  USE_CACHE: True
  USE_FULL_IMAGE: True
  BBOX_EXPAND_RATIO: 1.0
  IMAGE_SIZE: [480, 270]
  CENTER_IDX: 9
  FILTER_NO_CONTACT: True
  FILTER_DIST_THRESH: 0.005

MODEL: 
  TYPE: PiCRI
  PRETRAINED: null
  HG_STACKS: 2
  HG_BLOCKS: 1
  HG_CLASSES: 64
  MEAN_OFFSET: 0.010
  STD_OFFSET: 0.005
  VC_THRESH: 0.8
  OBJ_VERTS_MODE: gt
  OBJ_SCALE_FACTOR: 0.0001

  LOSS: 
    TYPE: CPFContactLoss
    CONTACT_LAMBDA_VERTEX_CONTACT: 10.0
    CONTACT_LAMBDA_CONTACT_REGION: 10.0
    CONTACT_LAMBDA_ANCHOR_ELASTI: 1.0
    FOCAL_LOSS_ALPHA: 0.90
    FOCAL_LOSS_GAMMA: 2.0
    REGION_FOCAL_TYPE: fphab


TRAIN:
  MANUAL_SEED: 1
  CONV_REPEATABLE: true
  EPOCH: 100
  OPTIMIZER: adam
  WEIGHT_DECAY: 0.0

  LR: 0.001
  FIND_UNUSED_PARAMETERS: False
  GRAD_CLIP_ENABLED: true
  GRAD_CLIP:
    TYPE: 2
    NORM: 1.0
  


